-- =====================================================================
-- L2 (gold) — Analytics tables
-- DT_WORKFORCE_360 is a dynamic table over L1; DT_PERFORMANCE / DT_LEARNING /
-- DT_RECRUITING are generated analytics tables. Requires a warehouse.
-- =====================================================================

create or replace schema SAP_PEOPLE_360.ANALYTICS;

create or replace TABLE SAP_PEOPLE_360.ANALYTICS.DT_LEARNING (
	EMPLOYEE_ID VARCHAR(16777216),
	DEPARTMENT VARCHAR(16777216),
	COURSE VARCHAR(16777216),
	CATEGORY VARCHAR(16777216),
	STATUS VARCHAR(16777216),
	HOURS NUMBER(38,0),
	COMPLETION_DATE DATE,
	SCORE FLOAT
);
create or replace TABLE SAP_PEOPLE_360.ANALYTICS.DT_PERFORMANCE (
	EMPLOYEE_ID VARCHAR(16777216),
	DEPARTMENT VARCHAR(16777216),
	REVIEW_YEAR NUMBER(38,0),
	RATING NUMBER(38,0),
	RATING_LABEL VARCHAR(16777216),
	POTENTIAL VARCHAR(16777216),
	IS_HIGH_POTENTIAL BOOLEAN,
	GOAL_COMPLETION_PCT NUMBER(38,0),
	REVIEW_STATUS VARCHAR(16777216)
);
create or replace TABLE SAP_PEOPLE_360.ANALYTICS.DT_RECRUITING (
	REQUISITION_ID VARCHAR(16777216),
	DEPARTMENT VARCHAR(16777216),
	JOB_TITLE VARCHAR(16777216),
	STATUS VARCHAR(16777216),
	OPENED_DATE DATE,
	APPLICATIONS NUMBER(38,0),
	INTERVIEWS NUMBER(38,0),
	OFFERS NUMBER(38,0),
	DAYS_OPEN NUMBER(38,0),
	IS_FILLED BOOLEAN,
	LOCATION VARCHAR(16777216)
);
create or replace dynamic table SAP_PEOPLE_360.ANALYTICS.DT_WORKFORCE_360(
	EMPLOYEE_ID,
	PERSON_UUID,
	MANAGER_ID,
	JOB_TITLE,
	PAY_GRADE,
	DEPARTMENT,
	DIVISION,
	LOCATION,
	COMPANY,
	GENDER,
	GENERATION,
	AGE,
	AGE_BAND,
	EMPLOYMENT_STATUS,
	EMPLOYEE_TYPE,
	EMPLOYMENT_TYPE,
	FLSA_STATUS,
	IS_MANAGER,
	DIRECT_REPORTS,
	IS_CRITICAL_POSITION,
	IS_FULL_TIME,
	FTE,
	ANNUAL_SALARY,
	SALARY_MIN,
	SALARY_MIDPOINT,
	SALARY_MAX,
	COMPA_RATIO,
	CURRENCY,
	HIRE_DATE,
	TERMINATION_DATE,
	HIRE_YEAR,
	TENURE_YEARS,
	TENURE_BAND,
	HEADCOUNT,
	TERMINATIONS,
	TERMINATION_REASON,
	EXTERNAL_HIRES,
	MOVEMENT_IN,
	MOVEMENT_OUT
) target_lag = 'DOWNSTREAM' refresh_mode = AUTO initialize = ON_CREATE warehouse = LOAD_WH
 as
SELECT
  USERID                                   AS EMPLOYEE_ID,
  PERSONUUID                               AS PERSON_UUID,
  MANAGERID                                AS MANAGER_ID,
  JOBTITLE                                 AS JOB_TITLE,
  PAYGRADE                                 AS PAY_GRADE,
  DECODE(DEPARTMENT,1,'Finance',2,'Human Resources',3,'Sales',4,'Marketing',5,'Engineering',
    6,'Operations',7,'Supply Chain',8,'Customer Service',9,'IT',10,'Legal',11,'R&D',12,'Procurement','Other') AS DEPARTMENT,
  DIVISION                                 AS DIVISION,
  LOCATION                                 AS LOCATION,
  DECODE(COMPANY,1000,'US Operations',2100,'EU Operations',5000,'Japan Operations','Other') AS COMPANY,
  GENDER, GENERATION,
  TOTALAGECALC                             AS AGE,
  CASE WHEN TOTALAGECALC<30 THEN 'Under 30' WHEN TOTALAGECALC<40 THEN '30-39'
       WHEN TOTALAGECALC<50 THEN '40-49' WHEN TOTALAGECALC<60 THEN '50-59' ELSE '60+' END AS AGE_BAND,
  EMPLOYMENTSTATUS                         AS EMPLOYMENT_STATUS,
  EMPLOYEETYPE                             AS EMPLOYEE_TYPE,
  EMPLOYMENTTYPE                           AS EMPLOYMENT_TYPE,
  FLSASTATUS                               AS FLSA_STATUS,
  MANAGERIALEMPLOYEE                       AS IS_MANAGER,
  DIRECTREPORTS                            AS DIRECT_REPORTS,
  CRITICALPOSITION                         AS IS_CRITICAL_POSITION,
  ISFULLTIMEEMPLOYEE                       AS IS_FULL_TIME,
  FTE,
  ANNUALSALARY                             AS ANNUAL_SALARY,
  MINIMUMPAY AS SALARY_MIN, MIDPOINT AS SALARY_MIDPOINT, MAXIMUMPAY AS SALARY_MAX,
  ROUND(ANNUALSALARY/NULLIF(MIDPOINT,0),3) AS COMPA_RATIO,
  SOURCECURRENCY                           AS CURRENCY,
  STARTDATE                                AS HIRE_DATE,
  ENDDATE                                  AS TERMINATION_DATE,
  YEAR(STARTDATE)                          AS HIRE_YEAR,
  TOTALORGTENURECALC                       AS TENURE_YEARS,
  CASE WHEN TOTALORGTENURECALC<1 THEN '<1 yr' WHEN TOTALORGTENURECALC<3 THEN '1-3 yrs'
       WHEN TOTALORGTENURECALC<5 THEN '3-5 yrs' WHEN TOTALORGTENURECALC<10 THEN '5-10 yrs' ELSE '10+ yrs' END AS TENURE_BAND,
  EOPHEADCOUNT                             AS HEADCOUNT,
  TERMINATIONS                             AS TERMINATIONS,
  MOVEOUTREASON                            AS TERMINATION_REASON,
  EXTERNALHIRES                            AS EXTERNAL_HIRES,
  MOVEMENTIN                               AS MOVEMENT_IN,
  MOVEMENTOUT                              AS MOVEMENT_OUT
FROM SAP_PEOPLE_360.SAP_BDC_L1.WORKFORCE;
